name: build-and-deploy
on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]
  # Allows the ability to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy all site contents to _site, exclude .git
        run: |
          mkdir ../_site
          touch ../_site/.git
          cp -n -ax * ../_site
          rm ../_site/.git
          mv ../_site .
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install minify@9.1.0
        run: npm install -g minify@9.1.0
      - name: Check minify version
        run: minify -v
      - name: Install minify-json
        run: npm install -g minify-json
      - name: Minify file pluto/index.html
        run: minify pluto/index.html > _site/pluto/index.html
      - name: Minify file pluto/main.js
        run: minify pluto/main.js > _site/pluto/main.js
      - name: Minify all JSON files already in _site/pluto/
        run: minify-json _site/pluto
      - name: Archive _site to artifacts.tar
        run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
        # Details on this at https://github.com/actions/deploy-pages
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v1
